name: Build

on:
  push:
    tags: [ "*" ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ "1.21" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      # ubuntu-latest

      - name: Build (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: go build -o ./fetch_comments_arm64 -v .

      - name: Upload artifact (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: fetch_comments_arm64
          path: ./fetch_comments_arm64

      # macos-latest

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: go build -o ./fetch_comments -v .

      - name: Upload artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: fetch_comments_mac
          path: ./fetch_comments_mac

      # windows-latest

      - name: Build (windows)
        if: matrix.os == 'windows-latest'
        run: go build -o ./fetch_comments_windows.exe -v .

      - name: Upload artifact (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: fetch_comments_windows.exe
          path: ./fetch_comments_windows.exe

  release:
    name: Release
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - run: tree artifacts/

      - run: mkdir dist
      - run: find artifacts/ -type f -print0 | xargs -0 mv -t dist/

      - run: ls -lisah dist/

      - name: Create Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: v${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets to Release
        uses: csexton/release-asset-action@v2
        with:
          pattern: "dist/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.release.outputs.upload_url }}
